### ISSUE TITLE
Missing build variables?

### ISSUE THREAD

**Issue by jandryuk** [OpenXT/openxt-manifest#14]
OpenXT do_build.sh sets some OE variables in local.conf.  This could be responsible for the missing build information.

https://github.com/OpenXT/openxt/blob/267c5a40c535085c733e65a1901236e606e88c14/do_build.sh#L129
```
                if [ "x$ID" != "x" ]; then
                    echo "XENCLIENT_BUILD = \"$ID\"" >> conf/local.conf
                else
                    echo "XENCLIENT_BUILD = \"$NAME\"" >> conf/local.conf
                fi

                cat >> conf/local.conf <<EOF
XENCLIENT_BUILD_DATE = "`date +'%T %D'`"
XENCLIENT_BUILD_BRANCH = "${BRANCH}"
XENCLIENT_VERSION = "$VERSION"
XENCLIENT_RELEASE = "$RELEASE"
XENCLIENT_TOOLS = "$XENCLIENT_TOOLS"

# dir for generated deb packages
XCT_DEB_PKGS_DIR := "${OE_BUILD_CACHE}/xct_deb_packages"
EOF
```

**Comment by eric-ch** [comment]
Sorry, this got left out.
This is now generated through by [bordel](https://github.com/apertussolutions/bordel/) at https://github.com/apertussolutions/bordel/blob/master/cmds/config#L49. Albeit, `OPENXT_BUILD_ID` is not that great as it is part of the template and not handled by `bordel`.

**Comment by jandryuk** [comment]
Yes, this was fixed a while ago.  Closing.
